#!/usr/bin/env zsh
# dotfiles/git/@install

###################################################################################################
# Setup

PROG=${(%):-%N}
DIR=$(cd $(dirname ${PROG}) && pwd)
DOTFILES=$(cd ${DIR} && cd .. && pwd)
PATH=${DOTFILES}/lib:${PATH}

###################################################################################################
# Symlinks

echo ${DOTFILES}
symlink ${DOTFILES}/git/.gitconfig ~/.gitconfig
