#!/usr/bin/env zsh
PROMPT='%F{241}%m ★%f  %F{226}%100c%f $(git_prompt_info) %F{241}➤%f  '

ZSH_THEME_GIT_PROMPT_PREFIX="%F{241}git(%F{147}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%F{241})%f"
ZSH_THEME_GIT_PROMPT_DIRTY=" %F{196}✗%f"
ZSH_THEME_GIT_PROMPT_CLEAN=""
