#!/usr/bin/env zsh
# dotfiles/zsh/@install

###################################################################################################
# Setup

PROG=${(%):-%N}
DIR=$(cd $(dirname ${PROG}) && pwd)
DOTFILES=$(cd ${DIR} && cd .. && pwd)

###################################################################################################
# Symlinks


# case "$(uname)" in
# 	'Linux' )
# 		;;
# 	'Darwin' )
# 		;;
# esac

###################################################################################################
# Install Files

cp -rf ${DIR}/.zshrc ${HOME}/.zshrc

rm -rf ${HOME}/.oh-my-zsh/custom/*
cp -rf ${DIR}/custom/* ${HOME}/.oh-my-zsh/custom/.

rm -rf ${HOME}/.oh-my-zsh/themes/*
cp -rf ${DIR}/themes/* ${HOME}/.oh-my-zsh/themes/.