#!/usr/bin/env zsh
# dotfiles/zsh/@install

###################################################################################################
# Setup

PROG=${(%):-%N}
DIR=$(cd $(dirname ${PROG}) && pwd)
DOTFILES=$(cd ${DIR} && cd .. && pwd)
PATH=${DOTFILES}/lib:${PATH}

###################################################################################################
# Symlinks

rm -f ~/.oh-my-zsh/custom/*

symlink ${DOTFILES}/zsh/custom.zsh ~/.oh-my-zsh/custom/custom.zsh
symlink '/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl' ~/bin/subl